"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "J. Fernando Sánchez"
email = "j@sanchezrada.es"

[[--scope]]
--when.repositories = ["~/git/work/tcs"]
[--scope.user]
name = "J. Fernando Sánchez"
email = "f.sanchez@thechannelstore.tv"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
l = ["log"]
s = ["status"]
f = ["git", "fetch"]
p = ["git", "push"]

[ui]
pager = "delta" #":builtin"
diff-formatter=":git"
paginate = "auto"
default-command = ["log", "--reversed"]

[merge-tools.delta]
diff-args=["--color-only", "--side-by-side", "$left", "$right", "--width=$width"]
