"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "J. Fernando Sánchez"
email = "j@sanchezrada.es"

[[--scope]]
--when.repositories = ["~/git/work/tcs"]
[--scope.user]
name = "J. Fernando Sánchez"
email = "f.sanchez@thechannelstore.tv"


[ui]
pager = "delta" #":builtin"
diff-formatter=":git"
paginate = "auto"

[merge-tools.delta]
diff-args=["--color-only", "--side-by-side", "$left", "$right", "--width=$width"]
